apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: utilityapi
  namespace: default
  labels:
    app: utilityapi
spec:
  selector:
    matchLabels:
      app: utilityapi
      namespace: default
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: utilityapi
    spec:
      containers:
      - name: utilityapi
        image: ulrichnilsson/utilityapi:latest
        ports:
        - containerPort: 80
      #imagePullPolicy: Always
